### ISSUE TITLE
Dear senior，I want to consult about Multi-input feature problem

### ISSUE THREAD

**Issue by dengjinyu123** [Ming-er/NeuralNILM_Pytorch#3]
I am sorry,I did not find out how to input a multi-featured .py file,such as P + Q + S

**Comment by Ming-er** [comment]
Hi! My apologies for the late reply. I must mention that, only dae, seq2point and bi-lstm support the multi-dimensional features as input now. You should import the corresponding model, and use it to process the power data.
I'll give you an example.  
If you want to use dae to process the P and Q of washing machine simultaneously, you should follow the below instructions and revise your code.

from nilmtk.api import API
import warnings
warnings.filterwarnings("ignore")
from nilmtk.disaggregate import MUL_DAE
e = {
  'power': {
    'mains': ['active', 'reactive'],
    'appliance': ['active']
  },
  'sample_rate': 6,
  'appliances': ['washing machine'],
  'pre_trained':False,
  'methods':{"MUL_DAE":MUL_DAE({'n_epochs':3,'batch_size':256})},
  ...
}

API(e)

If you like this repository, don't hesitate to star it. And if you have some problems, you can send emails to yiming@cau.edu.cn, I'll reply it as soon as possible.
