### ISSUE TITLE
Dear senior，I want to consult about the use of parameters for extracting load activations

### ISSUE THREAD

**Issue by HYuTing** [Ming-er/NeuralNILM_Pytorch#4]
Sorry to bother you.It is often mentioned in papers that device-specific parameters are passed to the get_activations() function in the NILMTK tool to extract device activations, but I can't find an example of using get_activations() in the code to extract activations.

**Comment by Ming-er** [comment]
Hi! My apologies for the late reply. I must mention that our repository 'NeuralNILM_Pytorch' is designed for conducting end2end deep learning energy disaggregation methods. So we won't include any manual feature extracting processes, such as the get_activations() function you mentioned.

**Comment by HYuTing** [comment]
> Hi! My apologies for the late reply. I must mention that our repository 'NeuralNILM_Pytorch' is designed for conducting end2end deep learning energy disaggregation methods. So we won't include any manual feature extracting processes, such as the get_activations() function you mentioned.

**Comment by HYuTing** [comment]
> Hi! My apologies for the late reply. I must mention that our repository 'NeuralNILM_Pytorch' is designed for conducting end2end deep learning energy disaggregation methods. So we won't include any manual feature extracting processes, such as the get_activations() function you mentioned.

Thank you for your answer, very helpful !
