### ISSUE TITLE
the function train_jointly() in api.py

### ISSUE THREAD

**Issue by zhgqcn** [Ming-er/NeuralNILM_Pytorch#5]
![image](https://user-images.githubusercontent.com/44897668/159654324-db1063d1-782c-47ae-873f-c64c68197f57.png)

- the note says 'This function has a few issues, which should be addressed soon'.
- Could you please tell me where is wrong?
- Thank you

**Comment by Ming-er** [comment]
Oh, you can ignore this sentence, these issues won't affect the normal use.
